# Dockerfile.nginx
FROM nginx:alpine

# Удалите стандартный конфигурационный файл Nginx
RUN rm /etc/nginx/conf.d/default.conf

# Копируйте ваш конфигурационный файл
COPY default.conf /etc/nginx/conf.d/
