# docker-compose.yml
version: '3.8'

services:
  web:
    build: .
    command: >
      sh -c "
      python manage.py migrate &&
      gunicorn possystem.wsgi:application --bind 0.0.0.0:8080
      "
    volumes:
      - .:/app
    expose:
      - "8080"
    env_file:
      - .env
    depends_on:
      - db

  nginx:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    volumes:
      - .:/app
      - ./default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8080:80"
    depends_on:
      - web

  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: possystem
      POSTGRES_USER: yourusername
      POSTGRES_PASSWORD: yourpassword

volumes:
  postgres_data:
