# Generated by Django 4.2.14 on 2024-07-17 07:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost', models.FloatField(verbose_name='Qiymət')),
                ('cash_or_card', models.CharField(choices=[('cash', 'Nağd'), ('card', 'Kart')], max_length=4, verbose_name='Ödəniş növü')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Satış tarixi')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Satış aparan işçi')),
            ],
        ),
        migrations.CreateModel(
            name='SaleProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pos.product', verbose_name='Satılan məhsul')),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='log.sale', verbose_name='Satış əməliyyat nömrəsi')),
            ],
        ),
        migrations.CreateModel(
            name='SaleProductRefund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Qaytarılma tarixi')),
                ('note', models.TextField(blank=True, null=True, verbose_name='Qeyd')),
                ('sale_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='log.saleproduct', verbose_name='Sale Product ID')),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseProductRefund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.FloatField(verbose_name='Say')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Geri qaytarılma tarixi')),
                ('note', models.TextField(blank=True, null=True, verbose_name='Qeyd')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Geri qaytaran işçi')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pos.product', verbose_name='Firmaya qaytarılan məhsul')),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Əməliyyat tarixi')),
                ('quantity', models.FloatField(verbose_name='Say')),
                ('refunded', models.BooleanField(default=False)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Alan işçi')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pos.product', verbose_name='Alınan məhsul')),
            ],
        ),
    ]
