# Generated by Django 4.1.5 on 2023-06-12 13:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pos', '0006_remove_firm_email_remove_firm_phone_number_and_more'),
        ('log', '0002_alter_purchaseproduct_employee_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PurchaseProductRefundLog',
            new_name='PurchaseProductRefund',
        ),
        migrations.AlterField(
            model_name='purchaseproduct',
            name='date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Əməliyyat tarixi'),
        ),
    ]
