# Generated by Django 4.1.5 on 2023-02-02 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cdate', models.DateTimeField(auto_now_add=True, verbose_name='Yaranma tarixi')),
                ('udate', models.DateTimeField(auto_now=True, verbose_name='Dəyişiklik tarixi')),
                ('ddate', models.DateTimeField(auto_now=True, verbose_name='Silinmə tarixi')),
                ('is_deleted', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=50, verbose_name='Mağaza adı')),
                ('unvan', models.TextField(max_length=100, verbose_name='Ünvan')),
            ],
            options={
                'ordering': ('-cdate',),
                'abstract': False,
            },
        ),
    ]
