# Generated by Django 4.1.5 on 2023-01-31 05:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0003_user_belongs_to_user_is_manager'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cdate', models.DateTimeField(auto_now_add=True, verbose_name='Yaranma tarixi')),
                ('udate', models.DateTimeField(auto_now=True, verbose_name='Dəyişiklik tarixi')),
                ('ddate', models.DateTimeField(auto_now=True, verbose_name='Silinmə tarixi')),
                ('is_deleted', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=50, verbose_name='Mağaza adı')),
                ('unvan', models.TextField(max_length=100)),
                ('manager', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='shop', to='user.user', verbose_name='Rəhbər')),
                ('user_create', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_creator', to='user.user', verbose_name='Daxil edən')),
                ('user_delete', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_delete', to='user.user', verbose_name='Silən')),
                ('user_update', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_update', to='user.user', verbose_name='Dəyişiklik edən')),
            ],
            options={
                'ordering': ('-cdate',),
                'abstract': False,
            },
        ),
    ]
