# Generated by Django 4.1.5 on 2023-01-31 12:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_alter_user_profile_picture'),
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shop',
            name='user_create',
        ),
        migrations.RemoveField(
            model_name='shop',
            name='user_delete',
        ),
        migrations.RemoveField(
            model_name='shop',
            name='user_update',
        ),
        migrations.CreateModel(
            name='UserLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_create', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_creator', to='user.user', verbose_name='Daxil edən')),
                ('user_delete', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_delete', to='user.user', verbose_name='Silən')),
                ('user_update', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_update', to='user.user', verbose_name='Dəyişiklik edən')),
            ],
        ),
    ]
