# Generated by Django 4.1.5 on 2023-02-19 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_shop_is_deleted'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shop',
            options={'verbose_name': 'Mağaza', 'verbose_name_plural': 'Mağazalar'},
        ),
    ]
