# Generated by Django 4.1.5 on 2023-06-07 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_shop_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Shop',
        ),
    ]
