# Generated by Django 4.2.14 on 2024-07-17 07:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Firm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Ad')),
                ('contact', models.CharField(blank=True, max_length=30, null=True, verbose_name='Əlaqə(tel. nömrəsi, e-poçta və s.)')),
            ],
            options={
                'verbose_name': 'Firma və ya individual şəxs',
                'verbose_name_plural': 'Firmalar və ya individual şəxslər',
            },
        ),
        migrations.CreateModel(
            name='UnitOfMeasure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('measure', models.CharField(max_length=50, verbose_name='Ölçü vahidi')),
                ('abbr', models.CharField(max_length=25, verbose_name='Qısaldılmış adı')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Ölçü vahidi',
                'verbose_name_plural': 'Ölçü vahidi',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cdate', models.DateTimeField(auto_now_add=True, verbose_name='Yaranma tarixi')),
                ('udate', models.DateTimeField(auto_now=True, verbose_name='Dəyişiklik tarixi')),
                ('ddate', models.DateTimeField(auto_now=True, verbose_name='Silinmə tarixi')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Məhsulun adı')),
                ('barcode', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Barkod')),
                ('picture', models.ImageField(blank=True, null=True, upload_to='images/product', verbose_name='Şəkil')),
                ('price', models.FloatField(verbose_name='Satış qiyməti (AZN)')),
                ('purchase_price', models.FloatField(verbose_name='Alış qiyməti (AZN)')),
                ('quantity', models.FloatField(verbose_name='Say/Miqdar')),
                ('is_deleted', models.BooleanField(default=False)),
                ('firm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pos.firm', verbose_name='Firma və ya individual şəxs')),
                ('measure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pos.unitofmeasure', verbose_name='Ölçü vahidi')),
                ('user_create', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_creator', to=settings.AUTH_USER_MODEL, verbose_name='Daxil edən')),
                ('user_delete', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_delete', to=settings.AUTH_USER_MODEL, verbose_name='Silən')),
                ('user_update', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_update', to=settings.AUTH_USER_MODEL, verbose_name='Dəyişiklik edən')),
            ],
            options={
                'verbose_name': 'Məhsul',
                'verbose_name_plural': 'Məhsullar',
            },
        ),
    ]
