# Generated by Django 4.1.5 on 2023-02-10 11:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0002_remove_shop_is_deleted'),
    ]

    operations = [
        migrations.CreateModel(
            name='Firm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Ad')),
                ('phone_number', models.CharField(max_length=30, verbose_name='Əlaqə')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.shop', verbose_name='Mağaza')),
            ],
        ),
        migrations.CreateModel(
            name='UnitOfMeasure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('measure', models.CharField(max_length=50, verbose_name='Ölçü vahidi')),
                ('abbr', models.CharField(max_length=25, verbose_name='Qısaldılmış adı')),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cdate', models.DateTimeField(auto_now_add=True, verbose_name='Yaranma tarixi')),
                ('udate', models.DateTimeField(auto_now=True, verbose_name='Dəyişiklik tarixi')),
                ('ddate', models.DateTimeField(auto_now=True, verbose_name='Silinmə tarixi')),
                ('name', models.CharField(max_length=100, verbose_name='Məhsul')),
                ('barcode', models.CharField(blank=True, max_length=50, null=True, verbose_name='Barkod')),
                ('picture', models.ImageField(upload_to='images/product', verbose_name='Şəkil')),
                ('price', models.FloatField(verbose_name='Qiymət')),
                ('quantity', models.FloatField(verbose_name='Say')),
                ('firm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pos.firm', verbose_name='Firma')),
                ('measure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pos.unitofmeasure', verbose_name='Ölçü vahidi')),
                ('user_create', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_creator', to=settings.AUTH_USER_MODEL, verbose_name='Daxil edən')),
                ('user_delete', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_delete', to=settings.AUTH_USER_MODEL, verbose_name='Silən')),
                ('user_update', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_update', to=settings.AUTH_USER_MODEL, verbose_name='Dəyişiklik edən')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cdate', models.DateTimeField(auto_now_add=True, verbose_name='Yaranma tarixi')),
                ('udate', models.DateTimeField(auto_now=True, verbose_name='Dəyişiklik tarixi')),
                ('ddate', models.DateTimeField(auto_now=True, verbose_name='Silinmə tarixi')),
                ('type', models.CharField(choices=[(1, 'Satılan'), (2, 'Geri qaytarılan'), (3, 'Firmadan alınan'), (4, 'Firmaya qaytarılan')], max_length=2, verbose_name='Tip')),
                ('note', models.TextField(blank=True, null=True, verbose_name='Qeyd')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pos.product', verbose_name='Məhsul')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Əməliyyat aparan işçi')),
            ],
            options={
                'ordering': ('-cdate',),
                'abstract': False,
            },
        ),
    ]
