# Generated by Django 4.1.5 on 2023-02-13 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Məhsulun adı'),
        ),
        migrations.AlterField(
            model_name='product',
            name='picture',
            field=models.ImageField(null=True, upload_to='images/product', verbose_name='Şəkil'),
        ),
        migrations.DeleteModel(
            name='Log',
        ),
    ]
