# Generated by Django 4.1.5 on 2023-02-19 14:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0002_alter_product_name_alter_product_picture_delete_log'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='firm',
            options={'verbose_name': 'Firma və ya individual şəxs', 'verbose_name_plural': 'Firmalar və ya individual şəxslər'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Məhsul', 'verbose_name_plural': 'Məhsullar'},
        ),
        migrations.AlterModelOptions(
            name='unitofmeasure',
            options={'verbose_name': 'Ölçü vahidi', 'verbose_name_plural': 'Ölçü vahidi'},
        ),
        migrations.AddField(
            model_name='firm',
            name='email',
            field=models.EmailField(blank=True, max_length=50, null=True, verbose_name='E-Poçta'),
        ),
        migrations.AlterField(
            model_name='product',
            name='firm',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pos.firm', verbose_name='Firma və ya individual şəxs'),
        ),
    ]
