# Generated by Django 4.1.5 on 2023-06-08 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0005_remove_firm_shop'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='firm',
            name='email',
        ),
        migrations.RemoveField(
            model_name='firm',
            name='phone_number',
        ),
        migrations.AddField(
            model_name='firm',
            name='contact',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Əlaqə(tel. nömrəsi, e-poçta və s.)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='barcode',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Barkod'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.FloatField(verbose_name='Qiymət (AZN)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='quantity',
            field=models.FloatField(verbose_name='Say/Miqdar'),
        ),
    ]
