# Generated by Django 4.1.5 on 2023-06-13 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0006_remove_firm_email_remove_firm_phone_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='purchase_price',
            field=models.FloatField(default=2, verbose_name='Alış qiyməti (AZN)'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.FloatField(verbose_name='Satış qiyməti (AZN)'),
        ),
    ]
