# Generated by Django 4.1.5 on 2023-06-13 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0007_product_purchase_price_alter_product_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
