# Generated by Django 4.1.5 on 2023-06-13 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0008_product_is_deleted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Məhsulun adı'),
        ),
    ]
