# Generated by Django 4.1.5 on 2023-02-01 07:24

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('cdate', models.DateTimeField(auto_now_add=True, verbose_name='Yaranma tarixi')),
                ('udate', models.DateTimeField(auto_now=True, verbose_name='Dəyişiklik tarixi')),
                ('ddate', models.DateTimeField(auto_now=True, verbose_name='Silinmə tarixi')),
                ('is_deleted', models.BooleanField(default=False)),
                ('profile_picture', models.ImageField(default='images/user/profilepictures.png', null=True, upload_to='images/user')),
                ('is_manager', models.BooleanField(default=False)),
                ('shop', models.ManyToManyField(to='app.shop', verbose_name='Rəhbər')),
            ],
            options={
                'ordering': ('-cdate',),
                'abstract': False,
            },
            bases=('auth.user', models.Model),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
