# Generated by Django 4.1.5 on 2023-02-13 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(default='images/user/profilepictures.png', null=True, upload_to='images/user', verbose_name='Profil şəkil'),
        ),
    ]
