# Generated by Django 4.1.5 on 2023-02-19 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_user_profile_picture'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'İşçi', 'verbose_name_plural': 'İşçilər'},
        ),
    ]
