# Generated by Django 4.1.5 on 2023-06-07 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_user_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='shop',
        ),
    ]
