# Generated by Django 4.1.5 on 2023-01-31 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_user_belongs_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(default='images/user/profilepictures.png', null=True, upload_to='images/user'),
        ),
    ]
